### ISSUE TITLE
Config doesn't save on Project64 1.6

### ISSUE THREAD

**Issue by awiss** [wermipls/pj64-wiiu-gcn#11]
I'm using this plugin with Project64 1.6 (which is the only version which works with an autosplitter I use), but the config doesn't seem to save on this version and resets every time p64 is closed and relaunched.

Seems like 1.6 doesn't even have a Config directory. I tried creating one but still don't see the .bin file there after I hit save config.

Happy to fix this myself, just wondering if there is a way to see logs/errors originating from the plugin? If I can find those I can probably fix this and put up a PR.

**Comment by wermipls** [comment]
hey, couple notes about config saving:
* program files (where pj64 1.6 is installed by default) is write protected on new versions of windows. this might be the reason you're having problems,
* determining the path is currently subtly broken as it uses current working directory as base, this can make the config/log folders end up in weird places under some circumstances. this is probably would be best fixed by deriving the path from `GetModuleFileName`, or frankly simpler and more foolproof, by just saving the config in %appdata% instead, which will solve the write permission woes as well

as for logs, by default they only get output to a text file, which is not particularly convenient when you can't get any files written lol. i would suggest putting a `OutputDebugString(msg)` call or similar in the dlog (log.h) function somewhere, the output then can be viewed using debugview: https://learn.microsoft.com/en-us/sysinternals/downloads/debugview

let me know if you have any other questions!

**Comment by awiss** [comment]
Thanks for the quick response!
I did manage to solve this, I got rid of the write protection but I think this was actually caused by windows doing some weird stuff with application shortcuts messing up the paths. Anyways when I launch Project64.exe directly it works fine now.
