### ISSUE TITLE
Add Rumble Support

### ISSUE THREAD

**Issue by imsl0wer** [wermipls/pj64-wiiu-gcn#13]
Only thing I'm still missing other than that great plugin <3

**Comment by wermipls** [comment]
this requires doing two things:
* handling raw communication for the accessory. from looking at the plugin spec, it should be possible to do without making the entire plugin raw, which is Good. otherwise it would require manually implementing controller pak support which is a fuck ton of unneccessary work
* implementing rumble support in the adapter code, this should be fairly simple

i'll try looking into it in a couple days but no promises :o)

**Comment by wermipls** [comment]
turned out a little more complicated than i anticipated, but it works! let me know if you encounter any issues, i haven't tested it extensively

**Comment by imsl0wer** [comment]
Yup works perfectly in Majora's Mask and Ocarina of Time. Thanks <3
