### ISSUE TITLE
Add the option from an older version: "Analog triggers"

### ISSUE THREAD

**Issue by moepunzie** [wermipls/pj64-wiiu-gcn#17]
Hello. Not an issue but an idea/wish for the plugin: Bring back the "analog triggers" option
I find it kind of hard to press down the actual button on the GameCube controller. I used the analog triggers with a super low threshold on older versions of the plugin.
I am talking about this option right here:

![grafik](https://github.com/wermipls/pj64-wiiu-gcn/assets/93618255/d95865e8-834c-4718-a402-ca7460d62088)

Thanks for consideration!

**Comment by wermipls** [comment]
hi, the option is still there, but rather than being hidden behind a toggle, you need to map the controls to "L/R Analog" instead of "L/R Button". it should function the same as in old versions, let me know if that's not the case
![image](https://github.com/wermipls/pj64-wiiu-gcn/assets/32251376/59b5bcce-cd31-415f-8dd3-d8c2003f8e99)

**Comment by bourff** [comment]
Oh, perfect! I looked through all the options in the window but didn't test this one.
Works just like the old option. Thanks for the quick response!
